


select * from JIRA_MINER;
select * from JIRA_FILTERS;
select * from JIRA_SEARCH;

select * from QC_DEFECT_DATA WHERE ERA_CREATED_DATE > '2015-01-01';

/*
drop table JIRA_MINER;
drop table JIRA_FILTERS;
drop table JIRA_SEARCH;
*/

show index from JIRA_FILTERS where Key_name = 'PRIMARY' ;



alter table JIRA_MINER add column MAX int(11);











CREATE TABLE JIRA_MINER(
    JIRA_MINER_ID INT(11) NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (JIRA_MINER_ID),

    DOMAIN VARCHAR(30) DEFAULT 'JIRA',
    PROJECT VARCHAR(100) NOT NULL,
    SAVE_TABLE VARCHAR(40) NOT NULL,
	SAVE_TABLE_PK VARCHAR(40) NOT NULL,
	CREDENTIALS VARCHAR(100) NOT NULL,
	BASE_URL VARCHAR(100) NOT NULL,
	MAX int(11) NOT NULL,

	ACTIVE BOOL DEFAULT TRUE,

    LAST_UPDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);


CREATE TABLE JIRA_FILTERS(
    JIRA_SEARCH_ID INT(11) NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (JIRA_SEARCH_ID),

	JIRA_MINER_ID INT(11),
	FOREIGN KEY (JIRA_MINER_ID) REFERENCES JIRA_MINER(JIRA_MINER_ID),

    JIRA_COLUMN VARCHAR(50),
    FILTER VARCHAR(50),

    LAST_UPDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);


CREATE TABLE JIRA_SEARCH(
    JIRA_SEARCH_ID INT(11) NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (JIRA_SEARCH_ID),

	JIRA_MINER_ID INT(11),
	FOREIGN KEY (JIRA_MINER_ID) REFERENCES JIRA_MINER(JIRA_MINER_ID),

    JIRA_COLUMN VARCHAR(50),
    DB_COLUMN VARCHAR(50),

    LAST_UPDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);


